### ISSUE TITLE
Request release of the code for Rainbow experiments

### ISSUE THREAD

**Issue by kaixin96** [openai/train-procgen#10]
Thanks for the great benchmark. Can you help release the code for experiments with Rainbow? Thank you.

Best regards

**Comment by christopherhesse** [comment]
I'm afraid we do not have plans to release that code currently.  You can check out [Dopamine](https://github.com/google/dopamine) which is a pretty official rainbow implementation as well as the rainbow hyperparameters from the procgen benchmark paper in section D.2.

**Comment by kaixin96** [comment]
@christopherhesse May I ask if you use ape-x since the original Rainbow is designed to run on single-GPU? Does each worker maintain their own replay buffer?

I am trying to reproduce the Rainbow results. Any advice on implementations is very appreciated. 

Thank you and best regards!

**Comment by christopherhesse** [comment]
It sounds like we used `anyrl-py`'s implementation, and each worker has its own independent replay buffer.  The parameters are synchronized using baselines `MpiAdamOptimizer` to provide the communication between the GPUs.

**Comment by kaixin96** [comment]
Thanks for your quick reply !
