### ISSUE TITLE
MPI error when running simultaneous training and testing

### ISSUE THREAD

**Issue by kaixin96** [openai/train-procgen#4]
The code runs smoothly when using `python -m train_procgen.train` but throws an error when using MPI. The error log is as follows:
```
Logging to /tmp/procgen
creating environment
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 66543 RUNNING AT 2a1b7906b5b2
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

```

Can you help me? Thank you.

**Comment by christopherhesse** [comment]
I followed the installation instructions in a new conda environment and it seemed to work fine with the following command:

`mpiexec -np 2 python -m train_procgen.train --env_name starpilot --num_levels 500 --test_worker_interval 2`

Are you running with different dependencies or running a different command than the one you pasted? The usual cause of the terminate error you pasted is providing an incorrect environment name.

**Comment by kaixin96** [comment]
Thank you. I tried again with a clean conda env and it works.
