### ISSUE TITLE
GPU OOM when running on manually specified devices 

### ISSUE THREAD

**Issue by kaixin96** [openai/train-procgen#5]
When running with manually specified `CUDA_VISIBLE_DEVICES` variable, the code seems to use much more memory in the first gpu than others, leading to OOM error. It runs without errors when I don't manually set gpus.

Can you help me? Thank you.

**Comment by christopherhesse** [comment]
Can you give an example of the command you are using?  If you're attempting to use multiple GPUs while also using `CUDA_VISIBLE_DEVICES`, you will likely have to make changes to `setup_mpi_gpus`: https://github.com/openai/train-procgen/blob/master/train_procgen/train.py#L68

**Comment by kaixin96** [comment]
Thanks for your reply. Modifying `setup_mpi_gpus` works. I was not familiar with MPI. It turns out we need to give different `CUDA_VISIBLE_DEVICES` to each process.
