### ISSUE TITLE
Missing Code For Training on A Fixed Sequence of Levels

### ISSUE THREAD

**Issue by KarlXing** [openai/train-procgen#7]
According to the [blog](https://openai.com/blog/procgen-benchmark/), you also have an experiment about the ablation with deterministic levels. If I'm correct, you set the use_sequential_levels label as True. Is it possible for you to release the code for that experiment? Or could you please give an example about environment setup? Thank you.

**Comment by kcobbe** [comment]
We haven't released code for that specific experiment, but I can walk you through what's necessary. You're correct that this requires setting the use_sequential_levels flag to True during training. You'll also need to set num_levels=1. Num levels is used to specify the number of possible seeds, and in this case we only want 1. Set start_level to any fixed value (this determines the particular seed you get). During testing, instead set num_levels=0 to remove the determinism. Also, remember to use the easy difficulty level distribution. To summarize:

training: {use_sequential_levels: True, num_levels: 1, start_level: YOUR_SEED, distribution_mode: "easy"}

testing: {use_sequential_levels: True, num_levels: 0, distribution_mode: "easy"}

**Comment by cometta** [comment]
@kcobbe  may i know is above parameters work for procgen 0.10.3 i set according to above during training but still i get different rewards
