### ISSUE TITLE
Specifications for training/testing in easy mode 

### ISSUE THREAD

**Issue by mklissa** [openai/train-procgen#9]
I was wondering how the curves of Figure 13 from the paper are obtained. The paper's Appendix D indicates that there is only one worker for the easy mode, but that would only provide us the "Train" results. Do you simply use "mpiexec np 2" and assign the second worker as a test_worker or is there another approach? Thanks.

**Comment by christopherhesse** [comment]
I believe there is always 1 test worker, so your approach should be fine.

**Comment by mklissa** [comment]
Awesome, thanks @christopherhesse !
